### ISSUE TITLE
install without pods

### ISSUE THREAD

**Issue by serjiogunit** [thanhcuong1990/react-native-SDWebImage#1]
Hello, how to install without using pods?

**Comment by thanhcuong1990** [comment]
@serjiogunit I think we should use pods for react-native 0.60+. 
But if you want to install without pods you can refer
https://facebook.github.io/react-native/docs/linking-libraries-ios
https://github.com/SDWebImage/SDWebImage/wiki/Installation-Guide#manual-installation-guide
